### DISCUSSION TITLE
Unable to access volume on DockerizedComponent

### DISCUSSION THREAD

**Discussion by rowanarts** [xlab-si/xopera-opera#218] [Q&A] [answered]
I want to mount a local folder to a docker container to persist data. 

So I added a dependency for the folder to the Ansible task (in `docker_component.yaml`), like so:
```
implementation:
  primary: playbooks/add_container.yml
  dependency:
    - "fs_data/"
```

When I create the component like so: 
```
fs:
  type: sodalite.nodes.DockerizedComponent
  properties:
    alias: { get_input: "fs-container-name" }
    hostname: { get_input: "fs-container-name" }
    image_name: { get_input: "fs-image-name" }
    # alias: "mongo"
    # hostname: "mongo"
    # image_name: "mongo"
    exposed_ports: { get_input: "FS_PORT_EXP" }
    ports: [{ get_input: "FS_PORT" }]
    volumes:
      - ./fs_data:/data/db
  requirements:
    - host: my-workstation
    - registry: docker-private-registry
```

It results in the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'mongod.lock'
```

Which leads to:
```
PermissionError: [Errno 1] Operation not permitted: '/tmp/tmp5tjd_k41/fs_data'
```

Is there anyone with experience who can help me with this error? 
- I'm not sure whether adding a dependency on `fs_data` is necessary.
- Running it WITHOUT the volume works perfectly.

[CSAR zip](https://github.com/xlab-si/xopera-opera/files/7142854/opera-package-76629b.zip)
