### ISSUE TITLE
Parallel execution does not stop if one execution branch fails.

### ISSUE THREAD

**Issue by alexmaslenn** [xlab-si/xopera-opera#100]
## Description
The idea behind parallelisation of workflow execution was that execution would stop as soon as it encounters an error. Currently execution continues if some nodes were scheduled for execution before an error was encountered.

## Steps
Deploy a service template with 2 independent nodes where an error occurs while deploying a first node, e.g
```yaml
topology_template:
  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    hello-2: # <- fail on this node
      type: hello_type
      properties:
        time: "2"
      requirements:
        - host: my-workstation     
        
    hello-3:
      type: hello_type
      properties:
        time: "1"
      requirements:
        - host: my-workstation  
```

## Current behaviour
xOpera would proceed to deploy other node.

## Expected results
xOpera should stop ASAP when encountering an error.
