### ISSUE TITLE
get_input function is not evaluated inside a map

### ISSUE THREAD

**Issue by alexmaslenn** [xlab-si/xopera-opera#102]
## Description
When `get_input` function is used inside a nested type, e.g. `map `property, then it is not evaluated and passed to playbook as it is.
## Steps
When deploying the following service template 
```yaml
node_types:

  hello_type:
    derived_from: tosca.nodes.Root
    properties:
      map1:
        type: map
        default: {}
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        operations:
          create:
            inputs:
              map1:  { default: { get_property: [ SELF, map1] } }
            implementation:
              primary: playbooks/create.yml

topology_template:

  inputs:
    marker:
      type: string

    hello-2: 
      type: hello_type
      properties:
        map1:
          test: { get_input: marker }
```
## Current behaviour
`get_input` function is not taken into account and `map1` variable value passed to playbook is `test: { get_input: marker }`
## Expected behaviour 
Value should take actual input

**Comment by anzoman** [comment]
Oh, thanks @alexmaslenn, interesting and a very good find.

**Comment by duelle** [comment]
I seem to have the same, or at least a similar, issue. The function `get_inputs` seems not to be evaluated in the list `env_vars` either.
![screenshot_aws_lambda](https://user-images.githubusercontent.com/7212186/94690310-7b27af80-031f-11eb-8f80-5661461bcd90.png)

**Comment by duelle** [comment]
Here's the `yaml` representation of the definition above:
```
    AwsLambdaFunction:
      type: radon.nodes.aws.AwsLambdaFunction
      metadata:
        x: "875"
        y: "93"
        displayName: "ThumbnailGenerator"
      properties:
        handler: "spblab.thumbgen.lambda.ThumbnailGenerationHandler"
        memory: 256
        name: "radon-particle-test"
        runtime: "java8"
        alias: "dev"
        statement_id: "lambda_test_permission01"
        zip_file: "thumbnail-generator-dev.jar"
        timeout: 300
        env_vars:
          THUMBNAIL_BUCKET: { get_input: target_bucket_name }
        concurrency: 0
      requirements:
        - host:
            node: AwsPlatform
            relationship: con_HostedOn_0
            capability: host
        - endpoint:
            node: AwsS3Bucket_2
            relationship: con_ConnectsTo_0
            capability: storage_endpoint
      artifacts:
        thumbnail-generator:
          type: radon.artifacts.archive.JAR
          file: /servicetemplates/radon.blueprints/ThumbnailGeneration/files/AwsLambdaFunction/thumbnail-generator/thumbnail-generator-dev.jar
```
