### ISSUE TITLE
Allow scaling operations for xOpera

### ISSUE THREAD

**Issue by cankarm** [xlab-si/xopera-opera#108]
xOpera needs an operation to initiate scaling. In CLI this should be a command ```opera scale -i notification.json``` which would accept a notification message from monitoring as an input. 
In SaaS version of xOpera, the scale would be initiated with a specific API call that would also accept the notification.

This current fix is used to explore options of how scaling should be implemented. The operation will execute a scaling playbook.

**Comment by anzoman** [comment]
Ok, instead of `-i` switch I would propose `-n` in order not to confuse this monitoring notification with inputs. So you specified that this `opera scale` command would execute an Ansible playbook. Which playbook is that? Would user also need to supply path to the playbook (e.g. `opera scale -n notifcation.json scaling-playbook.yaml`). And since this playbook would then execute scaling tasks it would probably need access to the JSON object from `notification.json` to see what monitoring has captured and based on that scaling up/down would be performed. So how would this JSON be passed to the playbook? Just as a normal variable which can be access with Jinja2? @sstanovnik probably you can give some additional info here.

**Comment by cankarm** [comment]
I thought about ```-n``` and for me is the same. I used ```-i``` instead, just because this is an input for scaling. If this content get's into the process as notification or just as a manual execution, I do not mind for now.

**Comment by anzoman** [comment]
I just ran into [TOSCA interface notifications ](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#DEFN_ELEMENT_NOTIFICATION_DEF) which might be helpful there with scaling since TOSCA notification definitions can be used to transmit external events to the TOSCA orchestrator. There is also an interesting section about [receiving asynchronous notifications](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#_Toc26969437).

**Comment by sstanovnik** [comment]
Based on what we've discussed this past week, I propose

```shell script
opera notify -n/--notification <notification file, likely but not necessarily json.json>
```

Opera then shouldn't process this but instead pass the notification directly to "the" playbook.

@anzoman makes a good point on choosing what playbook to execute. I imagine it's possible to configure multiple receivers, just looking at TOSCA? I think we need to limit ourselves to a single receiver, otherwise implementing this across the stack gets difficult, as whatever sends the notification would then also need to know which receiver to choose.

Let's agree on a very barebones example service template that can receive and process notifications just so we have the same picture for what this entails. I have no idea what that would look like, @anzoman you had an example of this already, right? Can you paste it here, stripping it down to the bare minimum?

When we have that, we can look at how to implement this concretely.

**Comment by anzoman** [comment]
@sstanovnik thanks for you vision of the `notify` command. You asked for the service template that can receive and process notifications.

The simple one for scaling up would be:

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  radon.nodes.OpenStack.VM:
    derived_from: tosca.nodes.Compute
    attributes:
      available_instances:
        type: integer
        default: 42
      available_space:
        type: integer
        default: 1000
    properties:
      name:
        type: string
      image:
        type: string
      flavor:
        type: string
      network:
        type: string
      key_name:
        type: string
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        operations:
          create:
            implementation: playbooks/create.yaml

interface_types:
  radon.interfaces.scaling.ScaleUp:
    derived_from: tosca.interfaces.Root
    operations:
      scale_up:
        inputs:
          adjustment: { default: { get_property: [ SELF, name ] } }
        description: Operation for scaling up.
        implementation: playbooks/scale_up.yaml

policy_types:
  radon.policies.scaling.ScaleUp:
    derived_from: tosca.policies.Scaling
    properties:
      cpu_upper_bound:
        description: The upper bound for the CPU
        type: float
        required: false
        constraints:
          - greater_or_equal: 80.0
      adjustment:
        description: The amount by which to scale
        type: integer
        required: false
        constraints:
          - greater_or_equal: 1
    targets: [ radon.nodes.OpenStack.VM ]
    triggers:
      radon.triggers.scaling:
        description: A trigger for scaling up
        event: scale_up_trigger
        target_filter:
          node: radon.nodes.OpenStack.VM
        condition:
          - not:
            - and:
              - available_instances: [ { greater: 42 } ]
              - available_space: [ { greater: 1000 } ]
        action:
          - call_operation:
              operation: radon.interfaces.scaling.ScaleUp.scale_up
              inputs:
                adjustment: { get_property: [ SELF, adjustment ] }

topology_template:
  node_templates:
    workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    openstack_vm:
      type: radon.nodes.OpenStack.VM
      properties:
        name: HostVM
        image: centos7
        flavor: m1.xsmall
        network: provider_64_net
        key_name: my_key
      requirements:
        - host: workstation
      capabilities:
        host_capability:
         properties:
           num_cpus: 1
           disk_size: 10 GB
           mem_size: 4096 MB

  policies:
    scale_up:
      type: radon.policies.scaling.ScaleUp
      properties:
        cpu_upper_bound: 90
        adjustment: 1
```

Here opera notify could check if the `cpu_upper_bound` is higher that 90 based on the notification (JSON) file and then the orchestrator would run the `playbooks/scale_up.yaml`.

The other example would feature [TOSCA interface notifications](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#DEFN_ELEMENT_NOTIFICATION_DEF) but I haven't yet prepared a simple TOSCA YAML example.

**Comment by anzoman** [comment]
I have stripped the upper TOSCA template example and now it looks like this:

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  radon.nodes.OpenStack.VM:
    derived_from: tosca.nodes.Compute
    properties:
      name:
        type: string
      image:
        type: string
      flavor:
        type: string
      network:
        type: string
      key_name:
        type: string
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        operations:
          create:
            implementation: playbooks/create.yaml

interface_types:
  radon.interfaces.scaling.ScaleUp:
    derived_from: tosca.interfaces.Root
    operations:
      scale_up:
        description: Ansible playbook for scaling.
        implementation: playbooks/scale.yaml

policy_types:
  radon.policies.scaling.ScaleUp:
    derived_from: tosca.policies.Scaling
    targets: [ radon.nodes.OpenStack.VM ]
    triggers:
      radon.triggers.scaling:
        description: A trigger for scaling up
        event: scale_up_trigger
        target_filter:
          node: radon.nodes.OpenStack.VM
        action:
          - call_operation:
              operation: radon.interfaces.scaling.ScaleUp.scale_up

topology_template:
  node_templates:
    workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    openstack_vm:
      type: radon.nodes.OpenStack.VM
      properties:
        name: HostVM
        image: centos7
        flavor: m1.xsmall
        network: provider_64_net
        key_name: my_key
      requirements:
        - host: workstation

  policies:
    scale_up:
      type: radon.policies.scaling.ScaleUp
```

@cankarm but if we want to try the AWS Lambda scaling as the targeted scaling unit, we can use this TOSCA template:

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  radon.nodes.aws_role:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      aws_region:
        type: string
        description: AWS region
      role_name:
        type: string
        description: Name of the AWS role
      role_description:
        type: string
        description: Description for created role
    attributes:
      role_arn:
        type: string
        description: AWS role arn identifier
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        inputs:
          aws_region: { default: { get_property: [SELF, aws_region] }, type: string}
          role_name: { default: { get_property: [SELF, role_name] }, type: string }
          role_description: { default: { get_property: [SELF, role_description] }, type: string }
        operations:
          create:
            implementation:
              primary: playbooks/create.yaml
              dependencies:
                - files/policy.json
    capabilities:
      aws_role_requirement:
        type: tosca.capabilities.Compute
        valid_source_types: [radon.nodes.aws_lambda]
    requirements:
      - host_requirement:
          capability: tosca.capabilities.Compute
          relationship: tosca.relationships.HostedOn

  radon.nodes.aws_s3_bucket:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      bucket_name:
        type: string
        description: The name of the bucket
      aws_region:
        type: string
        description: AWS region
    attributes:
      bucket_name:
        type: string
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        inputs:
          bucket_name: { default: { get_property: [SELF, bucket_name] }, type: string }
          aws_region: { default: { get_property: [SELF, aws_region] }, type: string }
        operations:
          create: playbooks/create.yaml
          delete: playbooks/delete.yaml
    requirements:
      - host_requirement:
          capability: tosca.capabilities.Compute
          relationship: tosca.relationships.HostedOn

  radon.nodes.aws_lambda:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      aws_region:
        type: string
        description: AWS region
      function_name:
        type: string
        description: Name of the function
      function_alias:
        type: string
        description: Alias for function
      permission_id:
        type: string
        description: Id of permission
      lambda_runtime:
        type: string
        description: Runtime for lambda (List of possible values - https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)
      lambda_handler:
        type: string
        description: Handler for lambda function
      lambda_timeout:
        type: string
        description: Function timeout in seconds
      lambda_memory:
        type: string
        description: Function memory in MB
      bucket_out_name:
        type: string
        description: The name of the bucket containing resized images
    attributes:
      function_arn:
        type: string
        description: AWS function arn
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        inputs:
          function_name: { default: { get_property: [SELF, function_name] }, type: string }
          aws_region: { default: { get_property: [SELF, aws_region] }, type: string }
          aws_role: { default: { get_attribute: [SELF, aws_role_requirement, role_arn] }, type: string }
          func_alias: { default: { get_property: [SELF, function_alias] }, type: string }
          permission_id: { default: { get_property: [SELF, permission_id] }, type: string }
          lambda_runtime: { default: { get_property: [SELF, lambda_runtime] }, type: string }
          lambda_handler: { default: { get_property: [SELF, lambda_handler] }, type: string }
          lambda_timeout: { default: { get_property: [SELF, lambda_timeout] }, type: string }
          lambda_memory: { default: { get_property: [SELF, lambda_memory] }, type: string }
          bucket_out_name: { default: { get_property: [SELF, bucket_out_name] }, type: string }
        operations:
          create:
            inputs:
              lambda_zip_artifact:
                description: Text file artifact input
                type: string
                default: { get_artifact: [ SELF, text_file ] }
            implementation: playbooks/create.yaml
          delete: playbooks/delete.yaml
    artifacts:
      lambda_zip_artifact:
        type: tosca.artifacts.File
        file: files/aws_lambda.zip
    requirements:
      - host_requirement:
          capability: tosca.capabilities.Compute
          relationship: tosca.relationships.HostedOn
      - aws_role_requirement:
          capability: tosca.capabilities.Node
          relationship: tosca.relationships.DependsOn
      - aws_bucket_out_requirement:
          capability: tosca.capabilities.Node
          relationship: tosca.relationships.DependsOn

  radon.nodes.aws_bucket_notification:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      aws_region:
        type: string
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        inputs:
          event_name: { default: radon_on_jpg_add, type: string }
          bucket_name: { default: { get_property: [SELF, bucket, bucket_name] }, type: string }
          lambda_function_arn: { default:  { get_attribute: [SELF, receives_notification, function_arn] }, type: string }
          events: { default: "s3:ObjectCreated:*", type: string }
          suffix: { default: ".jpg", type: string }
          region: { default: { get_property: [SELF, aws_region] }, type: string }
        operations:
          create:  playbooks/create.yaml
    requirements:
      - host_requirement:
          capability: tosca.capabilities.Compute
          relationship: tosca.relationships.HostedOn
      - aws_role_requirement:
          capability: tosca.capabilities.Node
          relationship: tosca.relationships.DependsOn
      - aws_bucket_in_requirement:
          capability: tosca.capabilities.Node
          relationship: tosca.relationships.DependsOn
      - aws_bucket_out_requirement:
          capability: tosca.capabilities.Node
          relationship: tosca.relationships.DependsOn
      - aws_lambda_requirement:
          capability: tosca.capabilities.Node
          relationship: tosca.relationships.DependsOn

interface_types:
  radon.interfaces.scaling.ScaleUp:
    derived_from: tosca.interfaces.Root
    operations:
      scale_up:
        description: Ansible playbook for scaling.
        implementation: playbooks/scale.yaml

policy_types:
  radon.policies.scaling.ScaleUp:
    derived_from: tosca.policies.Scaling
    targets: [ radon.nodes.aws_lambda ]
    triggers:
      radon.triggers.scaling:
        description: A trigger for scaling up AWS Lambda
        event: scale_up_trigger
        target_filter:
          node: radon.nodes.aws_lambda
        action:
          - call_operation:
              operation: radon.interfaces.scaling.ScaleUp.scale_up

topology_template:
  node_templates:
    workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    aws_role:
      type: radon.nodes.aws_role
      properties:
        aws_region: { get_input: aws_region }
        role_name: { get_input: role_name }
        role_description: { get_input: role_description }
      requirements:
        - host: workstation

    aws_s3_bucket_in:
      type: radon.nodes.aws_s3_bucket
      properties:
        bucket_name: { get_input: bucket_in_name }
        aws_region: { get_input: aws_region }
      requirements:
        - host_requirement: workstation

    aws_s3_bucket_out:
      type: radon.nodes.aws_s3_bucket
      properties:
        bucket_name: { get_input: bucket_out_name }
        aws_region: { get_input: aws_region }
      requirements:
        - host_requirement: workstation

    aws_lambda:
      type: radon.nodes.aws_lambda
      properties:
        aws_region: { get_input: aws_region }
        function_name: { get_input: function_name }
        function_alias: { get_input: function_alias }
        permission_id: { get_input: permission_id }
        lambda_runtime: { get_input: lambda_runtime }
        lambda_handler: { get_input: lambda_handler }
        lambda_timeout: { get_input: lambda_timeout }
        lambda_memory: { get_input: lambda_memory }
        bucket_out_name: { get_input: bucket_out_name }
      requirements:
        - host_requirement: workstation
        - aws_role_requirement: aws_role
        - aws_bucket_out_requirement: aws_s3_bucket_out

    bucket_notification:
      type: radon.nodes.aws_bucket_notification
      properties:
        aws_region: { get_input: aws_region }
      requirements:
        - host_requirement: workstation
        - aws_role_requirement: aws_role
        - aws_bucket_in_requirement: aws_s3_bucket_in
        - aws_bucket_out_requirement: aws_s3_bucket_out
        - aws_lambda_requirement: aws_lambda

  policies:
    scale_up:
      type: radon.policies.scaling.ScaleUp
``` 

So for the scaling part we can skip all the policy constraints at first and just call a playbook that would receive the monitoring outputs (e.g. JSON file or something else). We can pass this file to playbook as an input similar as we do with TOSCA artifacts or we can just copy it to the adjacent location like we for TOSCA operation dependencies. So we want to trigger a playbook that was linked to the TOSCA policy trigger definition. Maybe `opera notify` is not the best choice then. Maybe `opera trigger -n notification.json` could invoke all the TOSCA policy trigger operations (with notification.json being available within each of the operation). What do you think @sstanovnik?

**Comment by cankarm** [comment]
Maybe I'm wrong but I thought we would like ```opera notify notification.json``` to be a single notification point. We can have in first line of the file what this is (a trigger, hearbeat message, else, etc?) and then we focus on the content.

**Comment by anzoman** [comment]
@cankarm this is also possible, we can specify (using the flag or the positional argument) that and therefore limit the execution to a specific trigger like `opera notify/trigger -n notification.json -t radon.triggers.scaling`. In the comment above I just wanted to say that we should make this new command as general as possible so that it would not be too specific and that the triggers could be also used for other purposes apart from scaling.

**Comment by anzoman** [comment]
#130 will add `diff` and `redeploy` CLI commands. So there will be more opera commands and I think that we maybe don't even need a new one for scaling (we were thinking about `opera scale/notify/trigger`). Scaling can be seen as a process that is connected with redeploying some services with new parameters and so on. So an idea would be that we add an additional switch to `opera redeploy` (when it'll be implemented) - this flag could be used like this: `opera redeploy --triggers/t --notification/-n notification.json` (without -n all the triggers could be invoked) and would invoke certain triggers within TOSCA policies based on the submitted notification file (JSON) from monitoring service (Prometheus). By invoking I mean that this would execute Ansible playbooks that are linked to the those trigger operations. That would be the way for us to scale the application (if we would want more and also more complex CLI parameters it would still be better to have a separate command). What do you think?

**Comment by sydkbc** [comment]
Hello all.

Sorry in advance for the long post.
Based on the discussion above and in terms of interacting with the monitoring tool I made a rough sketch:

![image](https://user-images.githubusercontent.com/36516781/107371666-342ba100-6aed-11eb-8ddb-918b96444bea.png)

So the way I see it, the notify functionality can be either triggered manually (through CLI) or in the case of SaaS the triggering will happen based on the monitoring metrics.

This can be implemented in 2 ways:
- Prometheus pushes the metrics towards SaaS (time series in real time)
- Grafana API is set to generate a notification when the threshold described in the policy is violated.
   Subsequent of course the policy.tosca file will perform the checks but this way the implementation seems more efficient.

This is a matter of what do we want to implement so opinions are more than welcome.

One further thing is if there is a way to get information defined i the policy.tosca during the deployment.
For example, if in the Policy.tosca the thresholds are defined, can we somehow get these values when we deploy the monitoring tool (respective yml)? 
If this is the case both options can be implemented.

Any opinions?

**Comment by anzoman** [comment]
Hi @sydkbc many thanks for your opinion and a nice representation! Both scenarios you mentioned are possible. So, for the second scenario we can retrieve thresholds after the deployment as TOSCA outputs which can be printed out using `opera outputs` CLI command but during the deployment this would be harder.

Now, because TOSCA does not say explicitly anything really useful about scaling, the important part is how to implement this with xOpera, Ansible and TOSCA and I would like to get you opinion on that too. So, the initial thresholds will probably be defined as policy's TOSCA `properties` like this:

```yaml
interface_types:
  radon.interfaces.scaling.ScaleUp:
    derived_from: tosca.interfaces.Root
    operations:
      scale_up:
        description: Ansible playbook for scaling.
        implementation: playbooks/scale.yaml

policy_types:
  radon.policies.scaling.ScaleUp:
    derived_from: tosca.policies.Scaling
    properties:
      cpu_upper_bound:
        description: The upper bound for the CPU
        type: float
        required: false
        constraints:
          - greater_or_equal: 80.0
    targets: [ radon.nodes.aws.AwsLambda ]
    triggers:
      radon.triggers.scaling:
        description: A trigger for scaling up
        event: scale_up_trigger
        target_filter:
          node: radon.nodes.aws.AwsLambda
        action:
          - call_operation:
              operation: radon.interfaces.scaling.ScaleUp.scale_up
              inputs:
                adjustment: { get_property: [ SELF, adjustment ] }
```

When calling `opera notify -n notification.json` we would check the `notification.json`JSON file and if some of the keys from JSON matches the policy's property name and proceed if the limits are reached. The JSON object from `notification.json` file could also be exposed to the Ansible playbooks that will be triggered for scaling. 

@cankarm and @sstanovnik what do you think?

**Comment by cankarm** [comment]
Hi @sydkbc, @anzoman 

the sketch is very good and to remove different interpretations of it we might draw separate paths for CLI and SaaS to not confusing things too much.

In our vision the policy should define:

1. thresholds, which are used for configuring the monitoring (e.g. Prometheus) -the explicit configuration will probably be done by monitoring configuration TOSCA node using the content form policies (policy target node). 
2. trigger (with the corresponding event name that calls it and script for execution)
3. notification.yaml holds whatever monitoring sends (can hold only the monitoring readouts for logging reasons or something more that you would like to send to the scaling function).
4. event name calls trigger and the corresponding trigger-script.yaml for every trigger action. (in CLI directly with event name, while SaaS knows which trigger should be called by decoding the URL).

CLI call example would be

```console
opera notify -e <event name> -n <notification.json>
```
Sounds this reasonable?

**Comment by anzoman** [comment]
@cankarm this sounds great and I think we could give it a try:

1. as you said thresholds can be specified as properties within TOSCA policies. Those policies are then applied to nodes using `targets` keyname and xOpera could expose them to Ansible playbooks (that are linked to these nodes) and monitoring can be configured.
2. triggers will be connected to TOSCA interfaces where Ansible playbooks will be linked
3. the contents from the notification file (YAML, JSON or whatever) with monitoring results will be exposed to scaling playbook (this can be done with some Ansible variable such as `notification` which can then be accessed with Jinja2 ``{{ notification }}``)
4. TOSCA trigger event will probably be a used as an url parameter so that every trigger would have a corresponding API endpoint that could be used as a monitoring callback, so that for every event we would also have a separate notification file. 

The main thing here is that we won't use TOSCA properties for filtering, checking thresholds and finding out which TOSCA trigger to execute, but rather than that the parts of monitoring would be configured with predefined limits and with corresponding callbacks that would point to corresponding TOSCA triggers.

The final TOSCA service template for scaling of AWS Lambda could look like this: 

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:

  # other AWS TOSCA nodes and relationships are left out for brevity

  # AWS Lambda that we will monitor and scale
  radon.nodes.aws.AwsLambda:
    derived_from: tosca.nodes.SoftwareComponent
    # properties and attributes are left out for brevity
    interfaces:
      # standard interfaces for creating and deleting AWS Lambda function
      tosca.interfaces.node.lifecycle.Standard:
        operations:
          create: playbooks/create.yaml
          delete: playbooks/delete.yaml
      # custom TOSCA scaling interface with Ansible playbook for scaling up
      # we will expose the contents of notification.json file as Ansible variable to this playbook
      radon.interfaces.scaling:
        operations:
          # this playbook will be triggered with TOSCA trigger on policy 
          scale_up:  playbooks/scale_up.yaml

  # other monitoring TOSCA nodes and relationships are left out for brevity

  # node that configures AWS Lambda Prometheus monitoring 
  # can get threshold properties from policies with get_property TOSCA function
  radon.nodes.monitoring.configure:
    derived_from: tosca.nodes.SotfwareComponent
    # properties and attributes are left out for brevity
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        operations:
          configure: playbooks/configure.yaml
         inputs:
           cpu_upper_bound: { get_property: [ radon.policies.scaling.ScaleUp, cpu_upper_bound ] }

policy_types:
  # scaling up TOSCA policy with trigger
  radon.policies.scaling.ScaleUp:
    derived_from: tosca.policies.Scaling
    # properties with thresholds that are needed to configure monitoring
    # these are accessible from the connected nodes (with get_property function)
    properties:
      cpu_upper_bound:
        description: The upper bound for the CPU
        type: float
        required: false
    # target nodes that can access policies
    targets: [ radon.nodes.aws.AwsLambda, radon.nodes.monitoring.configure ]
    triggers:
      # scaling TOSCA trigger
      radon.triggers.scaling:
        description: A trigger for scaling up
        # event is required and the user will be able to select which event to execute
        # event will be used in xOpera API endpoint like `/notify?event=scale_up_trigger`
        # the whole endpoint (with http url param) will be a defined as a Prometheus callback 
        event: scale_up_trigger
        # filter nodes that can be scaled
        target_filter:
          node: radon.nodes.aws.AwsLambda
        # this is also required and point to the TOSCA interface with the corresponding playbook
        action:
          - call_operation: radon.interfaces.scaling.scale_up

topology_template:
  node_templates:
    workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    # other AWS node templates left out for brevity

    aws_lambda:
      type: radon.nodes.aws.AwsLambda
      # contents left out for brevity

    # other monitoring node templates left out for brevity

    configure_monitoring:
      type: radon.nodes.monitoring.configure
      # contents left out for brevity
  
  # with this we actually activate policies for usage
  # opera notify would policies and their triggers referenced here
  policies:
    scale_up:
      type: radon.policies.scaling.ScaleUp
      properties:
        cpu_upper_bound: 90
```

First `opera deploy` would be used to set up everything and to configure monitoring.
Then when monitoring detects that the limits are reached `opera notify --event scale_up_trigger  --notification notification.json` is invoked and opera would then execute the scaling Ansible playbook.

**Comment by cankarm** [comment]
That's very good @anzoman! Maybe we should add also "scale_down" script in this example, so it would be clear that needs to be defined in `radon.interfaces.scaling` and requires a corresponding policy and trigger in `policy_types`. This would also clarify that for each different kind of scaling (worker node, database, etc..) a separate set of scale-up and scale-down scripts would be required.

**Comment by anzoman** [comment]
@cankarm sure, the TOSCA template with `scale_down` could look like this:

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  # other AWS TOSCA nodes and relationships are left out for brevity
  radon.nodes.aws.AwsLambda:
    derived_from: tosca.nodes.SoftwareComponent
    interfaces:
      tosca.interfaces.node.lifecycle.Standard:
        operations:
          create: playbooks/create.yaml
          delete: playbooks/delete.yaml
      radon.interfaces.scaling:
        operations:
          scale_down: playbooks/scale_down.yaml
          scale_up: playbooks/scale_up.yaml

  # other monitoring TOSCA nodes and relationships are left out for brevity
  radon.nodes.monitoring.configure:
    derived_from: tosca.nodes.SotfwareComponent
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        operations:
          configure: playbooks/configure.yaml
          inputs:
            cpu_lower_bound: { get_property: [ radon.policies.scaling.ScaleDown, cpu_lower_bound ] }
            cpu_upper_bound: { get_property: [ radon.policies.scaling.ScaleUp, cpu_upper_bound ] }

policy_types:
  radon.policies.scaling.ScaleDown:
    derived_from: tosca.policies.Scaling
    properties:
      cpu_lower_bound:
        description: The lower bound for the CPU
        type: float
        required: false
    targets: [ radon.nodes.aws.AwsLambda, radon.nodes.monitoring.configure ]
    triggers:
      radon.triggers.scaling:
        description: A trigger for scaling up
        event: scale_down_trigger
        target_filter:
          node: radon.nodes.aws.AwsLambda
        action:
          - call_operation: radon.interfaces.scaling.scale_down

  radon.policies.scaling.ScaleUp:
    derived_from: tosca.policies.Scaling
    properties:
      cpu_upper_bound:
        description: The upper bound for the CPU
        type: float
        required: false
    targets: [ radon.nodes.aws.AwsLambda, radon.nodes.monitoring.configure ]
    triggers:
      radon.triggers.scaling:
        description: A trigger for scaling up
        event: scale_up_trigger
        target_filter:
          node: radon.nodes.aws.AwsLambda
        action:
          - call_operation: radon.interfaces.scaling.scale_up

topology_template:
  node_templates:
    workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    # other AWS node templates are left out for brevity
    aws_lambda:
      type: radon.nodes.aws.AwsLambda
      # contents left out for brevity

    # other monitoring node templates are left out for brevity
    configure_monitoring:
      type: radon.nodes.monitoring.configure
      # contents left out for brevity

  policies:
    scale_down:
      type: radon.policies.scaling.ScaleDown
      properties:
        cpu_lower_bound: 10
    scale_up:
      type: radon.policies.scaling.ScaleUp
      properties:
        cpu_upper_bound: 90
```

**Comment by anzoman** [comment]
@cankarm, @sstanovnik I have updated the TOSCA scaling template, which now looks like this:

<details><summary>scaling TOSCA service template</summary>
<p>

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  # other AWS TOSCA nodes and relationships are left out for brevity

  # AWS Lambda that we will monitor and scale
  radon.nodes.aws.AwsLambda:
    derived_from: tosca.nodes.SoftwareComponent
    # properties and attributes are left out for brevity
    interfaces:
      # standard interfaces for creating and deleting AWS Lambda function
      tosca.interfaces.node.lifecycle.Standard:
        operations:
          create: playbooks/create.yaml
          delete: playbooks/delete.yaml
      # custom TOSCA scaling interface with Ansible playbook for scaling up
      # we will expose the contents of notification.json file as Ansible variable to this playbook
      radon.interfaces.scaling:
        operations:
          # this playbook will be triggered with TOSCA trigger on policy
          scale_down: playbooks/scale_down.yaml
          scale_up: playbooks/scale_up.yaml

  # other monitoring TOSCA nodes and relationships are left out for brevity

  # node that configures AWS Lambda Prometheus monitoring
  # can get threshold properties from policies with get_property TOSCA function
  radon.nodes.monitoring.configure:
    derived_from: tosca.nodes.SoftwareComponent
    # properties and attributes are left out for brevity
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        operations:
          configure:
            implementation: playbooks/configure.yaml
            inputs:
              cpu_lower_bound:
                type: float
                default: { get_property: [ radon.policies.scaling.ScaleDown, cpu_lower_bound ] }
              cpu_upper_bound:
                type: float
                default: { get_property: [ radon.policies.scaling.ScaleUp, cpu_upper_bound ] }

policy_types:
  # scaling down TOSCA policy with scale down trigger
  radon.policies.scaling.ScaleDown:
    derived_from: tosca.policies.Scaling
    # properties with thresholds that are needed to configure monitoring
    # these are accessible from the connected nodes (with get_property function)
    properties:
      cpu_lower_bound:
        description: The lower bound for the CPU
        type: float
        required: false
        default: 10.0
    # target nodes that can access policies
    targets: [ radon.nodes.aws.AwsLambda, radon.nodes.monitoring.configure ]
    triggers:
      # scaling down TOSCA trigger
      radon.triggers.scaling.ScaleDown:
        description: A trigger for scaling up
        # event is required and the user will be able to select which event to execute
        # event will be used in xOpera API endpoint like `/notify?event=scale_down_trigger`
        # the whole endpoint (with http url param) will be a defined as a Prometheus callback
        event: scale_down_trigger
        # filter nodes that can be scaled
        target_filter:
          node: radon.nodes.aws.AwsLambda
        # this is also required and point to the TOSCA interface with the corresponding playbook
        action:
          - call_operation: radon.interfaces.scaling.scale_down

  # scaling up TOSCA policy with scale up trigger
  radon.policies.scaling.ScaleUp:
    derived_from: tosca.policies.Scaling
    # properties with thresholds that are needed to configure monitoring
    # these are accessible from the connected nodes (with get_property function)
    properties:
      cpu_upper_bound:
        description: The upper bound for the CPU
        type: float
        required: false
        default: 90.0
    # target nodes that can access policies
    targets: [ radon.nodes.aws.AwsLambda, radon.nodes.monitoring.configure ]
    triggers:
      # scaling up TOSCA trigger
      radon.triggers.scaling.ScaleUp:
        description: A trigger for scaling up
        # event is required and the user will be able to select which event to execute
        # event will be used in xOpera API endpoint like `/notify?event=scale_up_trigger`
        # the whole endpoint (with http url param) will be a defined as a Prometheus callback
        event: scale_up_trigger
        # filter nodes that can be scaled
        target_filter:
          node: radon.nodes.aws.AwsLambda
        # this is also required and point to the TOSCA interface with the corresponding playbook
        action:
          - call_operation: radon.interfaces.scaling.scale_up

topology_template:
  node_templates:
    workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    # other AWS node templates left out for brevity

    aws_lambda:
      type: radon.nodes.aws.AwsLambda
      # contents left out for brevity

    # other monitoring node templates left out for brevity

    configure_monitoring:
      type: radon.nodes.monitoring.configure
      # contents left out for brevity

  # with this we actually activate policies for usage
  # opera notify would policies and their triggers referenced here
  policies:
    - scale_down:
        type: radon.policies.scaling.ScaleDown
    - scale_up:
        type: radon.policies.scaling.ScaleUp

```

</p>
