### ISSUE TITLE
Concat does not work with nodes own values

### ISSUE THREAD

**Issue by mihaTrajbaric** [xlab-si/xopera-opera#112]
When using `concat` intrinsic function (`with opera==0.6.2.dev3`) it fails when trying to concatenate node's own values.

This works fine:
`attribute: { get_attribute: [ SELF, property ]}`

this also works fine:
`attribute: { concat: [ 'This is property: ', get_attribute: [ other_node, property ]]}`

but this fails with "Invalid value expression for concat or join function: 'get_attribute'":
`attribute: { concat: [ 'This is property: ', get_attribute: [ SELF, property ]]}`

Here is full test file:
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  hello_type:
    derived_from: tosca.nodes.SoftwareComponent
    attributes:
      attribute:
        type: string
    properties:
      property:
        type: string


topology_template:

  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    hello:
      type: hello_type
      attributes:
        attribute: { get_attribute: [ SELF, property ]}
        # this doesn't work
        # attribute: { concat: [ 'This is property: ', get_attribute: [ SELF, property ]]}
      properties:
        property: "ThatIsProperty"
      requirements:
        - host: my-workstation

  outputs:
    attribute:
      description: Value of attribute
      value: { get_attribute: [ hello, attribute ]}
```
