### ISSUE TITLE
Policies in service templates should be serialized as a list

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#115]
## Description
This issue describe the inconsistency spotted in opera's TOSCA YAML v1.3 parser. [Section 3.9 of TOSCA Simple Profile in YAML v1.3](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#_Toc26969450) states that `policies` keyname within the `topology_template` should be represented as an optional list of TOSCA policy definitions that apply to the topology template.

So, the syntax for TOSCA policies here should look like this:

```yaml
topology_template:
    node_templates:
    # left off for brevity

    policies:
      - policy1:
          type: tosca.policies.placement
          # left off for brevity
      - policy2:
          type: tosca.policies.placement
          # left off for brevity
      - policy3:
          type: tosca.policies.placement
          # left off for brevity
```

When we try to use that syntax and deploy it with opera, we get an error (`Expected map.`), saying that opera expected a YAML dictionary/map for the `policies` keyname. And by looking into opera's parser we soon realize that policies are not serialized as a list, but rather as a map which is in contradiction with the TOSCA standard and it needs to be fixed. 

## Steps
To fix the issue in the TOSCA parser, we should modify the content in `src/opera/parser/tosca/v_1_3/topology_template.py` and also fix any tests or examples that use the wrong synax. 

## Current behaviour
Right now opera treats policies in `topology_template` as YAML maps.

## Expected results
Opera's TOSCA parser should serialize policies as YAML lists.
