### ISSUE TITLE
Enable getting outputs from relationships 

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#119]
## Description
We know that opera works very well when we try to get outputs from node templates by running`opera outputs` (after the deployment with `opera deploy`). But what about the relationship templates? Outputs in the `topology_template` represent the optional map of output parameters for the Topology Template. Moreover, the outputs section provides a means to define the output parameters that are available from a TOSCA Simple Profile service template. It allows for exposing attributes of **node templates or relationship templates** within the containing topology_template to users of a service (from TOSCA section 3.9.2.4). So, according to this the outputs should work with relationship templates too.

Let's consider the following example:

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  radon.nodes.test:
    derived_from: tosca.nodes.Compute
    requirements:
      - host:
          capability: tosca.capabilities.Compute
          relationship: radon.relationships.test

relationship_types:
  radon.relationships.test:
    derived_from: tosca.relationships.HostedOn
    attributes:
      relationship_attribute:
        type: string
        default: Relationship attribute
    properties:
      relationship_property:
        type: string
        default: Relationship property

topology_template:
  inputs:
    host_ip:
      type: string
      default: localhost
    relationship_input:
      type: string
      default: Relationship input

  node_templates:
    my_workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: { get_input: host_ip }
        public_address: { get_input: host_ip }

    test_node:
      type: radon.nodes.test
      requirements:
        - host:
            node: my_workstation
            relationship: test_relationship

  relationship_templates:
    test_relationship:
      type: radon.relationships.test

  outputs:
    output_relationship_attribute:
      description: Relationship attribute output
      value: { get_attribute: [ test_relationship, relationship_attribute ] }
    output_relationship_property:
      description: Relationship property output
      value: { get_property: [ test_relationship, relationship_property ] }
    output_relationship_input:
      description: Relationship input output
      value: { get_input: relationship_input }
```

So here we have a test node that runs on another workstation node and they are connected with the `test_relationship` relationship template using the test node's requirements. Now in the end we just wanna get the outputs (attributes, properties and inputs) from the `test_relationship` template. If we try to deploy and get outputs with opera we get the following result:

```console
(.venv) anzoman@ubuntu:~/Desktop/xopera-opera$ opera deploy templates/test.yaml
[Worker_0]   Deploying my_workstation_0
[Worker_0]   Deployment of my_workstation_0 complete
[Worker_0]   Deploying test_node_0
[Worker_0]   Deployment of test_node_0 complete
(.venv) anzoman@ubuntu:~/Desktop/xopera-opera$ opera outputs
Node template 'test_relationship' does not exist.
```
 
Sadly this means that we are unable to get the desired outputs from the relationship template since the opera tries to search only for a node template.

## Steps
To enable getting relationship outputs to opera opera, we could take a look at  the code where relationship templates and instances are used and refactor it in a way that opera will search for a node or relationship when getting outputs.

## Current behaviour
Currently it is not possible to get outputs from the relationship templates.

## Expected results
To be able to use get outputs from  the relationship templates.
