### ISSUE TITLE
[Feature Request] Handle inputs for optional properties in interface definitions

### ISSUE THREAD

**Issue by v-yussupov** [xlab-si/xopera-opera#129]
## Description
It could be helpful to enhance handling of inputs in interface definitions for optional properties. In this case, Ansible tasks relying on such optional values will not fail, not breaking the deployment.

Consider the following example (based on [AwsLambdaFunction](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.aws/AwsLambdaFunction) Node Type from RADON Particles repository):
AwsLambdaFunction Node Type allows configuring concurrency using an optional `concurrency` property, which is later accessed in the `lambda_concurrency ` input definition using TOSCA's `get_property` intrinsic function as shown in Snippet 1. 

#### [Snippet 1] Excerpt of AwsLambdaFunction Node Type
```
node_types:
  radon.nodes.aws.AwsLambdaFunction:
    derived_from: radon.nodes.abstract.Function    
    properties:
      ...      
      concurrency:
        type: integer
        description: Function concurrency
        required: false
        constraints:
          - in_range: [ 0, UNBOUNDED ]
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        inputs:          
          lambda_concurrency:
            type: integer
            required: true
            default: { get_property: [ SELF, concurrency ] }
...
```

Since AWS allows optional configuration of concurrency for functions, the Ansible playbook responsible for deploying AwsLambdaFunction Node Templates has a dedicated part to configure the concurrency, which is intended to be triggered only if the `lambda_concurrency` input is defined as shown in Snippet 2. 

#### [Snippet 2] Excerpt of an Ansible Playbook responsible for deployment of AwsLambdaFunction Node Templates
```
---
- hosts: localhost
  tasks:
    ...
    - name: "Put concurrency of Lambda function on AWS : {{ function_name }}"
      command: >-
        aws lambda put-function-concurrency
          --function-name {{ function_name }}
          --reserved-concurrent-executions {{ lambda_concurrency }}
          --region {{ aws_region }}
      when: lambda_concurrency is defined
...
```

To summarize, the `concurrency` property is optional, whereas the `lambda_concurrency` input is required because the corresponding Ansible variable is checked in one of the Ansible tasks.

## Current Behavior
In cases when the concurrency value was not set in AwsLambdaFunction Node Templates, xopera throws an exception because it tries to access a property which does not exist although the `concurrency` property is designed to be optional.
As a workaround, on the type level we set a default value for concurrency to be 0 (not a valid value for AWS) and added checks in the Ansible task not to run if the value is 0. However, this basically results in enforcing the `concurrency` property to be set even if it's not needed.

## Desired Behavior
It would be helpful if xopera is able to set required inputs (with required=true) for optional properties that are not defined instead of raising exceptions.  In the aforementioned example, it would be sufficient to have an Ansible variable `lambda_concurrency` which is declared, but not set.
