### ISSUE TITLE
Possible mistake spotted in ObjectStorage TOSCA normative type definition

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#166]
## Description
The orchestrator treats TOSCA properties as required by default. This also applies for the properties that are from [TOSCA normative type definitions](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/cos01/TOSCA-Simple-Profile-YAML-v1.3-cos01.html#_Toc26969462) (e.g., Node, Relationship, Capability, Artifact, etc.) which are pre-defined and automatically imported ar the beginning of the orchestration. We have recently discovered that `tosca.nodes.Storage.ObjectStorage` normative type might has an error in its definition. The `maxsize` property is described to be optional, so `required` keyname on that property should be explicitly set to false or there should be a default value specified. But none of that is present in the type's definition, which is the following:

```yaml
tosca.nodes.Storage.ObjectStorage:
  derived_from: tosca.nodes.Abstract.Storage
  properties:
    maxsize:
      type: scalar-unit.size
      constraints:
        - greater_or_equal: 0 GB
  capabilities:
    storage_endpoint:
      type: tosca.capabilities.Endpoint
```

This means that opera treats `maxsize` as a required property because we use the normative type definition above.

![image](https://user-images.githubusercontent.com/41727816/105607498-60ca8380-5d9f-11eb-9975-801ed1eb8005.png)

## Steps
We can resolve this by adding `required: false` to `tosca.nodes.Storage.ObjectStorage` normative node type.

## Current behaviour
The `maxsize` property is required on TOSCA `tosca.nodes.Storage.ObjectStorage` normative type but it shouldn't be according to the documentation.

## Expected results
The `maxsize` property on TOSCA `tosca.nodes.Storage.ObjectStorage` should be optional.
_______
### Note
This issue was originally discovered in https://github.com/radon-h2020/xopera-opera/issues/14.
