### ISSUE TITLE
Fix definition error in `tosca.nodes.Database` normative type

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#177]
## Description
The orchestrator treats TOSCA properties as required by default. This also applies for the properties that are from [TOSCA normative type definitions](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/cos01/TOSCA-Simple-Profile-YAML-v1.3-cos01.html#_Toc26969462) (e.g., Node, Relationship, Capability, Artifact, etc.) which are pre-defined and automatically imported at the beginning of the orchestration. We have recently discovered that `tosca.nodes.Database` (from section 5.9.8) normative type might has an error in its definition. The `port` property is described to be optional, so `required` keyname on that property should be explicitly set to false or there should be a default value specified. 

![image](https://user-images.githubusercontent.com/41727816/107337858-2eb56300-6abb-11eb-94c5-a975a6c64d50.png)

But none of that is present in the type's definition, which is the following:

```yaml
tosca.nodes.Database:
  derived_from: tosca.nodes.Root
  properties:
    name:
      type: string
      description: the logical name of the database
    port:
      type: integer
      description: the port the underlying database service will listen to for data
    user:
      type: string
      description: the optional user account name for DB administration
      required: false
    password:
      type: string
      description: the optional password for the DB user account
      required: false
  requirements:
    - host:
        capability: tosca.capabilities.Compute
        node: tosca.nodes.DBMS
        relationship: tosca.relationships.HostedOn
  capabilities:
    database_endpoint:
      type: tosca.capabilities.Endpoint.Database
```

This means that opera treats `port` as a required property because we use the normative type definition above.

## Steps
We can resolve this by adding `required: false` to `tosca.nodes.Database` normative node type.

## Current behaviour
The `port` property is required on TOSCA `tosca.nodes.Database` normative type but it shouldn't be according to the documentation.

## Expected results
The `port` property on TOSCA `tosca.nodes.Database` should be optional.
_______
### Note
This issue was originally discovered in https://github.com/radon-h2020/xopera-opera/issues/14.
