### ISSUE TITLE
Feature Request: Concat support for get_attribute functions

### ISSUE THREAD

**Issue by duelle** [xlab-si/xopera-opera#181]
In order to create an output for further processing by CTT, we would like to use a concatenation of multiple attributes. Unfortunately, it seems as if that was currently not supported.

Intended use in the output: `{ concat: [ { get_attribute: [ AwsApiGateway_0, endpoint_url ] }, { get_attribute: [ con_ApiGatewayTriggers_0, endpoint ] } ] }`

Currently, this leads to the following error message when executing `opera outputs`: 
```
% opera outputs
Invalid value expression for concat or join function: 'get_attribute'
```

Using a single get_attribute function (e.g., `{ get_attribute: [ AwsApiGateway_0, endpoint_url ] }`) works without a problem.

**Comment by anzoman** [comment]
Hi @duelle, thanks for opening this.

We have an example with [intrinsic functions](https://github.com/xlab-si/xopera-examples/tree/master/tosca/intrinsic-functions) I where we also use multiple TOSCA functions, so I believe that the problem is not in the implementation of `concat` intrinsic TOSCA function. More likely you are accessing some nonexistent or unspecified attribute because in these cases opera  can return `Invalid value expression for concat or join function`. Please take a look at your TOSCA service template again and try to access those attributes in the outputs without intrinsic functions first. If this does not help we can dig deeper.

**Comment by duelle** [comment]
Thanks @anzoman for the hint. I further investigated the issue and found out that probably not the `concat` function is failing but one of the functions inside that refers to a relationship.

Here is an excerpt from a service template where I want to access a property:
```
  relationship_templates:
    con_ApiGatewayTriggers_0:
      type: radon.relationships.aws.ApiGatewayTriggers
      properties:
        endpoint: "/todos"
        http_methods: "get"
```

In this scenario, neither `{ get_property: [ con_ApiGatewayTriggers_0, endpoint ] }` `{ get_attribute: [ con_ApiGatewayTriggers_0, endpoint ] }` worked. They just reported that there would be no such property/attribute. Am I missing something to make this functions work in a relationship context?

**Comment by anzoman** [comment]
@duelle getting attributes and properties from relationships should be possible with opera (like in this [relationship-outputs](https://github.com/xlab-si/xopera-examples/tree/master/tosca/relationship-outputs) example) and I've also tried this inside intrinsic functions and it worked.

If I try to deploy some simple TOSCA template with one node and one relationship and without playbooks like this one:

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  radon.nodes.test:
    derived_from: tosca.nodes.Compute
    attributes:
      node_attribute:
        type: string
        default: Default node attribute
    requirements:
      - host:
          capability: tosca.capabilities.Compute
          relationship: radon.relationships.test

relationship_types:
  radon.relationships.test:
    derived_from: tosca.relationships.HostedOn
    attributes:
      relationship_attribute:
        type: string
        default: Default relationship attribute
    properties:
      relationship_property:
        type: string
        default: Default relationship property

topology_template:
  inputs:
    host_ip:
      type: string
      default: localhost

  node_templates:
    my_workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: { get_input: host_ip }
        public_address: { get_input: host_ip }

    test_node:
      type: radon.nodes.test
      requirements:
        - host:
            node: my_workstation
            relationship: test_relationship

  relationship_templates:
    test_relationship:
      type: radon.relationships.test
      attributes:
        relationship_attribute: Relationship attribute
      properties:
        relationship_property: Relationship property

  outputs:
    output_node_attribute:
      description: Node attribute output
      value: { get_attribute: [ test_node, node_attribute ] }
    output_relationship_attribute:
      description: Relationship attribute output
      value: { get_attribute: [ test_relationship, relationship_attribute ] }
    output_relationship_property:
      description: Relationship property output
      value: { get_property: [ test_relationship, relationship_property ] }
    concat_output:
      description: Concatenate all attributes and properties
      value: { concat: [ { get_attribute: [ test_node, node_attribute ] },
                         { get_attribute: [ test_relationship, relationship_attribute ] },
                         { get_property: [ test_relationship, relationship_property ] } ] }
```

I get this result:

```console
(.venv) $ opera deploy test.yaml
[Worker_0]   Deploying my_workstation_0
[Worker_0]   Deployment of my_workstation_0 complete
[Worker_0]   Deploying test_node_0
[Worker_0]   Deployment of test_node_0 complete
(.venv) $ opera outputs
concat_output:
  description: Concatenate all attributes and properties
  value: Default node attributeRelationship attributeRelationship property
output_node_attribute:
  description: Node attribute output
  value: Default node attribute
output_relationship_attribute:
  description: Relationship attribute output
  value: Relationship attribute
output_relationship_property:
  description: Relationship property output
  value: Relationship property
```

I can't really see where your problem originates from. You can paste your full service template/CSAR here and we can try to investigate further.
