### ISSUE TITLE
Opera validate fails to catch missing input

### ISSUE THREAD

**Issue by mihaTrajbaric** [xlab-si/xopera-opera#193]
Opera validate command with inputs parameter is supposed to validate service template with inputs.

Consider following example:
```yaml
topology_template:
  inputs:
    marker:
      type: string

  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    hello1:
      type: hello_type
      properties:
        marker: { get_input: marker }
        location: /tmp/playing-opera/hello1
      requirements:
        - host: my-workstation
```

It has input `marker` without default value. If I validate it with input.yaml file without marker field (for instance with empty inputs file), validation would be a success although TOSCA template (in combination with inputs) is not valid:
```shell script
$ opera validate -i inputs.yaml service.yaml
Validating service template...
Done.

```
Of course, it fails during deployment.
```shell script
$ opera deploy service.yaml
[Worker_0]   Deploying my-workstation_0
[Worker_0]   Deployment of my-workstation_0 complete
[Worker_0]   Deploying hello1_0
[Worker_0]     Executing create on hello1_0
Error processing node hello1_0: Cannot use an unset value: marker
```

I think validation should catch errors like this, especially since it works in opposite direction (it throws `Undeclared inputs` for inputs in inputs.yaml file that are not declared in service template)
