### ISSUE TITLE
Support for outputs in topology_template

### ISSUE THREAD

**Issue by cankarm** [xlab-si/xopera-opera#22]
Current version of xOpera (0.5.2) does not support output section in the topology template. The following example is accepted by the application, but nothing happens. 

Example:
```
tosca_definitions_version: tosca_simple_yaml_1_3
topology_template:
  node_templates:
    db_server:
      type: tosca.nodes.Compute
      capabilities:
        # Host container properties
        host:
          properties:
            # Compute properties
            num_cpus: 5
            mem_size: 2048  MB
            disk_size: 10 GB
            mem_size: 4096 MB
  outputs:
    disk_size:
      description: The size of the disk
      value: { get_attribute: [ db_server, disk_size ] }
```

Preferred/expected behavior:
```
$ opera outputs --yaml
disk_size:
  description:  The size of the disk
  value: 10 GB
```
