### ISSUE TITLE
Assigning the value of a parameter definition unsupported

### ISSUE THREAD

**Issue by philippemerle** [xlab-si/xopera-opera#223]
The following service template:
```
tosca_definitions_version: tosca_simple_yaml_1_3
node_types:
  MyNodeType:
    derived_from: tosca.nodes.Root
    properties:
      my_property:
        type: string
    interfaces:
      Standard:
        operations:
          create:
            inputs:
              parameter:
                type: string
                value: { get_property: [SELF, my_property] }
topology_template:
  node_templates:
    node:
      type: MyNodeType
      properties:
        my_property: HelloWorld
```
can not be validated by opera:
```sh
$ opera validate unsupported_features/parameter_value.yaml
Validating service template...
parameter_value.yaml:14:17: [PropertyDefinition] Invalid keys: value
```

Assigning the value of a parameter definition seems to be unsupported by the opera parser, doesn't it?
