### ISSUE TITLE
Invalid assigment of the defaut of a parameter definition

### ISSUE THREAD

**Issue by philippemerle** [xlab-si/xopera-opera#225]
Into various service templates, e.g. [examples/hello/service.yaml](https://github.com/xlab-si/xopera-opera/blob/master/examples/hello/service.yaml), we could find definitions like:
```
node_types:
  hello_type:
    derived_from: tosca.nodes.SoftwareComponent
    interfaces:
      Standard:
        inputs:
          marker:
            default: { get_input: marker }
            type: string
        operations:
          create: playbooks/create.yaml
          delete: playbooks/delete.yaml
```

But `default: { get_input: marker }` is an invalid assigment because the assigned part (`{ get_input: marker }`) should be a value (e.g. `1`, `hello`, `true`, list, map, etc.) and not an expression or function call. See [Section 3.6.14 of TOSCA 1.3](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#DEFN_ELEMENT_PARAMETER_DEF).

In this example, `default: { get_input: marker }` should be replaced by `value: { get_input: marker }` because assigning an expression or function call to `value` is allowed by the TOSCA 1.3 grammar.
