### ISSUE TITLE
Attach playbook to Compute node without defining a new type

### ISSUE THREAD

**Issue by abitrolly** [xlab-si/xopera-opera#237]
Is it possible to execute playbook when `tosca.nodes.Compute` node template is deployed, without defining a new type?

Using modified example from https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#_Toc26969423

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

topology_template:
  node_templates:
    db_server:
      type: tosca.nodes.Compute
      interfaces:
        Standard:
          configure: scripts/my_own_configure.sh
```

`opera validate` errors out with this.

```bash
Validating service template...
mysql.yml:11:11: [InterfaceDefinitionForTemplate] Invalid keys: configure
```

**Comment by anzoman** [comment]
Hi and thanks for asking this. So, as I can see from TOSCA's documentation a lot of examples are not complete and quite some of them use older TOSCA versions (e.g., 1.0). 

I think that your example above is missing `operations` keyword for TOSCA interface you defined.

![slika](https://user-images.githubusercontent.com/41727816/151333128-3b6dd59c-9540-4b5c-8804-9859ef8ae90e.png)

You can probably try this:

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

topology_template:
  node_templates:
    db_server:
      type: tosca.nodes.Compute
      interfaces:
        Standard:
          operations:
            configure: scripts/my_own_configure.sh
```

And also note that xOpera currently supports only Ansible for running interface operations and we have a plan for adding other executors (e.g., bash, python) in the future.

**Comment by abitrolly** [comment]
@anzoman are you sure that the example about **interface definition** can be applied here? Above this example, standard refers to **sub-classing behavior**, which I believe I am doing.

![image](https://user-images.githubusercontent.com/8781107/151521800-3e41e42a-0b38-44b0-a553-683459155db2.png)

If this example is invalid, why nobody from consortia is interested in updating the invalid spec?

**Comment by abitrolly** [comment]
Perhaps @lauwers can answer the last question.

**Comment by lauwers** [comment]
Hi Anatoli, the TOSCA TC is hard at work on TOSCA v2.0. We realize that some of the examples in the v1.3 specification have errors, but getting corrections approved through the OASIS standardization process is fairly cumbersome and we decided our efforts would be better spent by focusing on the quality of the v2.0 spec. As part of this process, we plan on managing all examples in the TOSCA git repo at https://github.com/oasis-open/tosca-community-contributions so they can be run through various parsers and validators. We have just started this effort. As you can imagine there is a fair bit of work involved and we welcome and encourage anyone to contribute and participate if possible, ideally by joining the TOSCA TC. 
Thanks, Chris

**Comment by abitrolly** [comment]
@lauwers thanks for the proposal. TOSCA TC list holds addresses from major IT company domains. It looks like both OASIS and TC members are all sponsored by one entity or another, and the thought of doing this job sacrificing my time for free feels very miserable. So unless there is some serious funding involved, I have to refuse.

**Comment by abitrolly** [comment]
@anzoman this doesn't work.
```
tosca_definitions_version: tosca_simple_yaml_1_3

topology_template:
  node_templates:
    db_server:
      type: tosca.nodes.Compute
      interfaces:
        Standard:
          operations:
            configure: scripts/my_own_configure.sh
```

First is fails with this.
```
opera.error.ParseError: [Path] Path scripts/my_own_configure.sh does not exist.
[[Command exited with 1]]
```

And then the file is created, with this.
```
opera.error.ParseError: [NodeTemplate] Undeclared operations: configure.
[[Command exited with 1]]
```
