### ISSUE TITLE
How to deploy to other IP than localhost?

### ISSUE THREAD

**Issue by abitrolly** [xlab-si/xopera-opera#242]
`opera deploy` runs all notebooks on `localhost`. I tried to set `public_address` and `private_address`, but they are ignored.
```
  node_templates:
    myserver:
      type: tosca.nodes.Compute
      attributes:
        public_address: 3.12.3.1
        private_address: 3.12.3.1
```
So how to deploy to different IP?
