### ISSUE TITLE
Extended grammar for requirement relationship assignment unsupported

### ISSUE THREAD

**Issue by philippemerle** [xlab-si/xopera-opera#253]
For the following service template
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
topology_template:
  node_templates:
    compute:
      type: tosca.nodes.Compute
      requirements:
      - local_storage:
          node: storage
          relationship:
            properties:
              location: /path_to_access_the_storage_from_the_compute
    storage:
      type: BlockStorage
      properties:
        name: storage
```
opera raises an error
```sh
$ opera validate issue.yaml 
Validating service template...
issue.yaml:8:11: [RequirementAssignment] Expected a relationship template name as a 'relationship' value.
```
So the second table in Section 3.8.2.1 and the whole Section 3.8.2.2.3 of TOSCA 1.3 seem to be not supported.
