### ISSUE TITLE
Add support for policy targets and triggers

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#32]
Currently it is possible to declare TOSCA policy definition inside the `topology_template` section of the TOSCA service template but there is no support for policy targets and triggers so I thought that I'd be nice to have them and to be able to define a policy like in the example below.

```yaml
<policy_name>:
  type: <policy_type_name>
  description: <policy_description>
  metadata:
    <map of string>
  properties:
    <property_assignments>
  targets: [<list_of_policy_targets>]
  triggers:
    <trigger_definitions>
```
