### ISSUE TITLE
Add support for get_artifact TOSCA function

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#59]
## Description
xOpera orchestration tool supports several [TOSCA functions](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/cos01/TOSCA-Simple-Profile-YAML-v1.3-cos01.html#_Toc26969452) at the moment such as `get_attribute`, `get_property`, `get_input` which are really useful. But we are still lacking the parser support for some of the TOSCA functions. Amongst them probably the most desired one would be the `get_artifact` TOSCA function which is used to retrieve an artifact location between TOSCA entities defined in the same TOSCA service template. So as a user I would definitely want to use my prepared orchestration artifacts (for instance zipped FaaS function files) directly in a service template by linking them with `get_artifact: [ <modelable_entity_name>, <artifact_name>, <location>, <remove> ]`. 

## Steps
To implement this we would need to update our parser and provide the support for this function in a similar way as it is provided for the currently supported TOSCA functions.

## Current behaviour
Currently xOpera does not recognize `get_artifact` function.

## Expected results
To be able to parse and use `get artifact` TOSCA function in templates like in the example below:

```yaml
node_templates:
  wordpress:
    type: tosca.nodes.WebApplication.WordPress
    ...
    interfaces:
      Standard:
        configure:
          create:
            implementation: wordpress_install.sh
            inputs:
              wp_zip: { get_artifact: [ SELF, zip ] }
    artifacts:
      zip: /data/wordpress.zip
```
