### ISSUE TITLE
Consider enabling single TOSCA interface operation calls

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#62]
## Description
This suggestion is directly related to [TOSCA interface operations](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/cos01/TOSCA-Simple-Profile-YAML-v1.3-cos01.html#_Toc26969470) and their usage within the orchestrator. 

Currently if user calls xOpera orchestrator with `opera deploy` command it invokes the following TOSCA Standard interface node operations (from tosca.interfaces.node.lifecycle.Standard) and also TOSCA Configure interface relationship operations (from tosca.interfaces.relationship.Configure):

1. create
2. pre_configure_source
3. pre_configure_target
4. configure
5. post_configure_source
6. post_configure_target
7. start

When called with `opera undeploy` the following occurs:

1. stop
2. delete

So from that we can see that TOSCA operations in xOpera are connected and ordered. This is all great but I want to propose a new feature (if this is sensible)  where it would be possible to trigger the TOSCA operations (for instance create, configure, start, stop, delete, ...) individually. This feature could be used when one wants to define separate orchestration steps for deploying, configuring, and executing and wants to run them independently.

## Steps
To implement this we would need to update opera CLI commands and the part where these TOSCA operations are being called.

So these operation calls can be implemented either within own commands like:
`opera {deploy|undeploy|create|configure|start|stop|delete}` 

or perhaps as an (optional) subcommands such as:
`opera deploy --operation {create|configure|start}` or 
`opera undeploy --operation {stop|delete}`.

## Current behaviour
Right now xOpera does not offer calling TOSCA operations separately.

## Expected results
To be able to invoke TOSCA operations individually.

**Comment by anzoman** [comment]
@cankarm as we talked - this is just an idea but this operation calls can be also related to calling manually defined interface operations and could be used for (auto)scaling.

For example if you define an interface like this:

```yaml
interface_types:
  radon.interfaces.scaling:
    derived_from: tosca.interfaces.Root
    operations:
      scale:
        inputs:
          adjustment: { default: { get_property: [ SELF, name ] } }
        description: Operation for scaling.
        implementation: playbooks/scale_out.yaml
```

It maybe useful to call it inside TOSCA triggers and also separately with opera command.
