### ISSUE TITLE
Requirement assignment is omitted if not present in node_type requirement definition list

### ISSUE THREAD

**Issue by alexmaslenn** [xlab-si/xopera-opera#63]
## Description
If a service template has a node template with requirement assignment that does not have a matching requirement definition in corresponding node type, this requirement is simply omitted, and template execution proceeds as if this requierment assignment was never defined.
## Prerequisites
- `opera` installed
- `service.yaml` TOSCA Service Template containing node template that has a requirement assignment referring to another node template, but without proper requirement definition present in node_type.  
```
tosca_definitions_version: tosca_simple_yaml_1_3
topology_template:
  node_templates:
    node_1:
      type: tosca.nodes.SoftwareComponent   
    node_2:
      type: tosca.nodes.SoftwareComponent  
      requirements:
        - dependency: node_1      
    node_3:
      type: tosca.nodes.SoftwareComponent  
      requirements:
        - dependency_not_defined: node_1  
```
The first requirement assignment is present in the execution tree (as **dependency** requirement definition is defined in tosca.nodes.Root), while the second **dependency_not_defined** is not

## Steps
- User runs deploy `opera deploy service.yaml`
## Current behavior
 - xOpera proceeds with deployment.
## Expected behavior
- xOpera returns a parser error.
