### ISSUE TITLE
Duplicate node_template names

### ISSUE THREAD

**Issue by alexmaslenn** [xlab-si/xopera-opera#64]
## Description
If a service template has 2 node template with same node template names defined, one of them is omitted, and template execution proceeds without error. According to section **3.1.3.1 Additional Requirements**
>  Duplicate Template names within a Service Template’s Topology Template SHALL be considered an error.
## Prerequisites
- `opera` installed
- `service.yaml` TOSCA Service Template containing 2 node templates with same name.
```
tosca_definitions_version: tosca_simple_yaml_1_3
topology_template:
  node_templates:
    node_1:
      type: tosca.nodes.SoftwareComponent   
    node_1:
      type: tosca.nodes.SoftwareComponent 
```

## Steps
- User runs deploy `opera deploy service.yaml`
## Current behavior
 - xOpera proceeds with deployment.
## Expected behavior
- xOpera returns a parser error.
