### ISSUE TITLE
Add support for TOSCA workflows

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#77]
## Description
This issue is concerning adding the support for the TOSCA Workflows, which from the perspective of the TOSCA template represent the (optional) YAML map of imperative workflow definitions for the topology template. 

[TOSCA Workflows](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/cos01/TOSCA-Simple-Profile-YAML-v1.3-cos01.html#_Toc26969478) can be used to deploy, manage or undeploy TOSCA topology template. There are declarative and imperative workflows. Declarative ones are already supported since they are automatically generated by the opera orchestrator during the process of template instantiation. Imperative workflows are on the other hand specified manually by the user in order to define his own orchestration workflow which is usually not similar to the declarative one. 

And this is what we probably want to have in the future. These workflows are useful also because they can be triggered by TOSCA policies on deployment or on undeployment or even during runtime, manually, or automatically. It is also important to abide by the note in the TOSCA standard orchestrators will execute a single workflow at a time on a topology to guarantee that the defined workflow can be consistent and behave as expected.

## Steps
To implement the TOSCA Workflows we would have to update our TOSCA YAML parser so that opera will be able to parse these workflows and then we will also have to update the order and execution of these operations within nodes and relationships that are part of the topology. Here I surely did not mention everything we would have to do to support this new feature but certainly there will be a lot of work to do in order to support fully this.

## Current behaviour
Right now opera does not support (imperative) workflow definitions.

## Expected results
To be able to use other imperative TOSCA workflows within TOSCA topology templates.

### Note

I am  attaching one relatively simple TOSCA Workflows example (from TOSCA Simple Profile in YAML section _7.3.2.1_):

```yaml
topology_template:
  node_templates:
    my_server:
      type: tosca.nodes.Compute

    mysql:
      type: tosca.nodes.DBMS.MySQL
      requirements:
        - host: my_server
      interfaces:
        tosca.interfaces.nodes.custom.Backup:
          operations:
            backup: backup.yaml

  workflows:
    backup:
      description: Performs a snapshot of the MySQL data.
      steps:
        my_step:
          target: mysql
          activities:
            - call_operation: tosca.interfaces.nodes.custom.Backup.backup
```
