### ISSUE TITLE
Type keyname is not required when declaring input variables for a single operation

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#83]
## Description
When it comes to [Passing information as inputs to Interfaces and Operations](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#_Toc26969435) there are two ways of specifying inputs:

- **declaring input variables for all operations on a single interface**:

```yaml
<interface_definition_name>:
  type: <interface_type_name>
  inputs:
    <property_definitions>
  operations:
    <operation_definitions>
  notifications:
    <notification definitions>
```

- **declaring input variables for a single operation**:

```yaml
<operation_name>:
   description: <operation_description>
   implementation: <Operation implementation definition>
   inputs:
     <property_definitions>
      outputs:
         <attribute mappings>
```

So for both inputs are seen as property definitions which means that `type` keyname is required.

When testing this with the latest 0.5.8 version of opera I get the following result:

- declaring input variables for all operations on a single interface:

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  node_type_1:
    derived_from: tosca.nodes.SoftwareComponent
    interfaces:
      Standard:
        inputs:
          marker:
            default: { get_input: marker1 }
            type: string
        operations:
          create: playbooks/create1.yaml

topology_template:
  inputs:
    marker1:
      type: string
      default: default-marker1

  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    node_type_1:
      type: node_type_1
      requirements:
        - host: my-workstation
```

If I forget to specify `type` keyname for `marker` input opera answers with `[PropertyDefinition] Missing required fields: type` which is just fine.

- declaring input variables for a single operation:

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  node_type_2:
    derived_from: tosca.nodes.SoftwareComponent
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        operations:
          create:
            inputs:
              marker:
                default: { get_input: marker2 }
            implementation: playbooks/create2.yaml

topology_template:
  inputs:
    marker2:
      type: string
      default: default-marker2

  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    node_type_2:
      type: node_type_2
      requirements:
        - host: my-workstation
```

If I skip `type` keyname for `marker` input  here opera just proceeds with the deployment. 

## Current behaviour
Right now opera doesn't require `type` keyname when declaring input variables for a single operation.

## Expected results
To throw an error when input variable for a single operation doesn't have `type` keyname.
