### ISSUE TITLE
Add support for TOSCA Intrinsic functions

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#86]
## Description
[Intrinsic functions](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/csprd01/TOSCA-Simple-Profile-YAML-v1.3-csprd01.html#_Toc9262317) can be useful when manipulating data within the TOSCA template.   

There are currently three functions of this kind that will need to be supported:

1. **concat**

This is used when you want to concatenate two or more string values or strings that are result of other TOSCA functions (like `get_attribute`, `get_property` or `get_input`).

```yaml
outputs:
  description: Concatenate the URL for a server from other template values
  server_url:
  value: { concat: [ 'http://',
                     get_attribute: [ server, public_address ],
                     ':',
                     get_attribute: [ server, port ] ] }
```

2. **join**

This will be used to combine an array of strings into a single string (with an optional delimiter).

```yaml
outputs:
   example1:
       # Result: prefix_1111_suffix
       value: { join: [ ["prefix", 1111, "suffix" ], "_" ] }
   example2:
       # Result: 9.12.1.10,9.12.1.20
       value: { join: [ { get_input: my_IPs }, “,” ] } 
```

3. **token**

Used on a string to parse out (tokenize) substrings separated by one or more token characters within a larger string.

```yaml
outputs:
   webserver_port:
     description: the port provided at the end of my server’s endpoint’s IP address
     value: { token: [ get_attribute: [ my_server, data_endpoint, ip_address ], ‘:’, 1 ] }
```

## Steps
To implement this we would need to update opera's TOSCA parser and probably add a similar behaviour as we have for property and attribute TOSCA functions (like `get_attribute`, `get_property` and `get_input`).

## Current behaviour
Right now xOpera does not support any of intrinsic functions

## Expected results
To be able to invoke TOSCA intrinsic functions (concat, join, token).
_________
cc @dradx
