### ISSUE TITLE
Raise an exception when targeting more than one instance via the same requirement

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#88]
## Description
When defining node type's requirements as capabilities it is only possible to create the relationship between two nodes via the same requirement within the same node template.  Sometime users would want to connect more than one nodes (of different types) to the same node within the same requirement. However, this cannot survive through TOSCA template deployment since the relationships between nodes must be defined by using different requirements. For example in the TOSCA template below we try to link nodes `hello1` and `hello2` to the node `hello3` but we use the same requirement `input_component` for both of them:

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  hello_type_1:
    attributes:
      attribute1:
        type: string
        default: attribute1
    derived_from: tosca.nodes.SoftwareComponent

  hello_type_2:
    attributes:
      attribute2:
        type: string
        default: attribute2
    derived_from: tosca.nodes.SoftwareComponent

  hello_type_3:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      property1:
        type: string
      property2:
        type: string
    requirements:
      - input_component:
          capability: tosca.capabilities.Node
          node: tosca.nodes.SoftwareComponent
          relationship: tosca.relationships.DependsOn

topology_template:
  node_templates:
    my-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    hello1:
      type: hello_type_1
      requirements:
        - host: my-workstation

    hello2:
      type: hello_type_2
      requirements:
        - host: my-workstation

    hello3:
      type: hello_type_3
      properties:
        property1: { get_attribute: [ SELF, input_component, attribute1 ] }
        property2: { get_attribute: [ SELF, input_component, attribute2 ] }
      requirements:
        - host: my-workstation
        - input_component: hello1
        - input_component: hello2

  outputs:
    output_prop1:
      description: Property output
      value: { get_property: [ hello3, property1 ] }
    output_prop2:
      description: Property output
      value: { get_property: [ hello3, property2 ] }
```

When we run this with `opera deploy` opera proceeds with the deployment without any error. And when we want to print out the outputs to check whether the connection to both nodes was successful and we were able to access their attributes, we finally get an error saying: `Targeting more than one instance via 'input_component'.` which should appear before the deployment was started.

## Steps
To fix this we would probably need to update opera's parser to search for duplicate requirements within the same node template and then throw an error.

## Current behaviour
Right now opera proceeds with the deployment when targeting more than one instance via the same requirement that can have only occurrence.

## Expected results
The orchestrator should throw an error when targeting more than one instance within the same requirement that can have only occurrence.
_________
cc @dradx, @MysteriousWolf

**Comment by miwurster** [comment]
Hi @anzoman, IMHO a node template like the one in your example

```
hello3:
  type: hello_type_3
  properties:
    property1: { get_attribute: [ SELF, input_component, attribute1 ] }
    property2: { get_attribute: [ SELF, input_component, attribute2 ] }
  requirements:
    - host: my-workstation
    - input_component: hello1
    - input_component: hello2
```

is totally fine according to what the standard defines. As long as your ReqDef on type `hello_type_3` defines that the `input_component` req is `UNBOUNDED` (or > 2) this should be a valid configuration.

Due to the fact that you can have a list of reqs in the template, I would expect that xopera processes such a config without any error.

**Comment by anzoman** [comment]
Hi, @miwurster thanks, yes, as we talked the requirements are defined in TOSCA as a list and not as map/set so this is a valid template. @matejart can you give us your opinion too to be sure that we are truly right? 

If this is ok then we will not do any changes in this manner but we will still have to fix `opera outputs` command (which currently returns `Targeting more than one instance via 'input_component'.` if you use the same requirement name twice or more) to be able to recognize and distinguish the requirements with the same name.

**Comment by anzoman** [comment]
@miwurster after going through the TOSCA standard again, I have actually come to a different conclusion about this. So yes from the viewpoint of YAML syntax this is a totally valid configuration (because requirements are parsed as YAML list which allows multiple occurrences of the elements with the same YAML keys). But this is not the same with TOSCA. As mentioned before TOSCA states that: [_Duplicate names for the following keynames within Types or Templates SHALL be considered an error_](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/cos01/TOSCA-Simple-Profile-YAML-v1.3-cos01.html#_Toc26969442). According to the [RFC 2119](https://tools.ietf.org/html/rfc2119) SHALL = MUST.

![tosca_additional_reqs](https://user-images.githubusercontent.com/41727816/91940256-76a7b100-ecf7-11ea-8a96-4190c94b18cc.png)

Even further, when you go to the [requirement definition](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/cos01/TOSCA-Simple-Profile-YAML-v1.3-cos01.html#_Toc26969448) section this is warned about again.

![tosca_requirements](https://user-images.githubusercontent.com/41727816/91940245-73142a00-ecf7-11ea-9c95-ff65879fb29e.png)

So based on all this, the only time when the same requirement keynames can occur within the requirements list, is when the `occurrences` parameter (which is a range/interval of two numbers) has its end number set to more that 1 (this of course also applies when wet to UNBOUNDED). But by default this keyname is set to: `occurrences: [1,1]` and in this case only one occurrence of so called `requirement_definition_name` can be used. All in all the PR #90 is going in the right way, but I think we will need to add check for occurrences and the distinction between the requirements that have the same names.

**Comment by anzoman** [comment]
To be completely sure, how the orchestrator should treat this, I'm giving two examples:

**1. single requirement**:

This example shows that the requirement `my_requirement` within `hello_type_3` does not have specified `occurrences` keyname which (according to TOSCA) means that `occurrences` defaults to [1,1] so that this requirement can occur only one time. And in this case it occurred two times within the `hello3` node template, so opera should raise an error.

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  hello_type_1:
    derived_from: tosca.nodes.SoftwareComponent

  hello_type_2:
    derived_from: tosca.nodes.SoftwareComponent

  hello_type_3:
    derived_from: tosca.nodes.SoftwareComponent
    requirements:
      - my_requirement:
          capability: tosca.capabilities.Node
          node: tosca.nodes.SoftwareComponent
          relationship: tosca.relationships.DependsOn

topology_template:
  node_templates:
    hello1:
      type: hello_type_1

    hello2:
      type: hello_type_2

    hello3:
      type: hello_type_3
      requirements:
        - my_requirement: hello1
        - my_requirement: hello2
```

**2. unbounded requirements**:

Here the occurrences range for `my_requirement` within `hello_type_3` is zero to UNBOUNDED which means that the requirement can occur zero or multiple times. And in this case it occurred two times within the `hello3` node template, so opera should proceed with the deployment without any errors.

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  hello_type_1:
    derived_from: tosca.nodes.SoftwareComponent

  hello_type_2:
    derived_from: tosca.nodes.SoftwareComponent

  hello_type_3:
    derived_from: tosca.nodes.SoftwareComponent
    requirements:
      - my_requirement:
          capability: tosca.capabilities.Node
          node: tosca.nodes.SoftwareComponent
          relationship: tosca.relationships.DependsOn
           occurrences: [0, UNBOUNDED]

topology_template:
  node_templates:
    hello1:
      type: hello_type_1

    hello2:
      type: hello_type_2

    hello3:
      type: hello_type_3
      requirements:
        - my_requirement: hello1
        - my_requirement: hello2
```

**3. multiple occurrences for the requirement**:

Here the `occurrences` keyname for `my_requirement` within `hello_type_3` is set to [2,2] which means that the requirement must occur exactly two times within the same node_template that derives from the `hello_type_3`. And in this case it occurred exactly two times within the `hello3_first` node template and also exactly two times within the `hello3_second` node template, which is ok, so opera can proceed with the deployment without an error.

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  hello_type_1:
    derived_from: tosca.nodes.SoftwareComponent

  hello_type_2:
    derived_from: tosca.nodes.SoftwareComponent

  hello_type_3:
    derived_from: tosca.nodes.SoftwareComponent
    requirements:
      - my_requirement:
          capability: tosca.capabilities.Node
          node: tosca.nodes.SoftwareComponent
          relationship: tosca.relationships.DependsOn
           occurrences: [0, UNBOUNDED]

topology_template:
  node_templates:
    hello1:
      type: hello_type_1

    hello2:
      type: hello_type_2

    hello3_first:
      type: hello_type_3
      requirements:
        - my_requirement: hello1
        - my_requirement: hello2

    hello3_second:
      type: hello_type_3
      requirements:
        - my_requirement: hello1
        - my_requirement: hello2
```
